# Generated by Django 4.2.25 on 2025-10-10 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "0001_initial"),
        ("notifications", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativa"),
                            ("paused", "Pausada"),
                            ("completed", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_paused", models.BooleanField(db_index=True, default=False)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Imediato"),
                            ("business_days", "Apenas Dias Úteis"),
                            ("business_hours", "Horário Comercial"),
                            ("custom_period", "Período Personalizado"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("morning_start", models.TimeField(blank=True, null=True)),
                ("morning_end", models.TimeField(blank=True, null=True)),
                ("afternoon_start", models.TimeField(blank=True, null=True)),
                ("afternoon_end", models.TimeField(blank=True, null=True)),
                ("skip_weekends", models.BooleanField(default=True)),
                ("skip_holidays", models.BooleanField(default=True)),
                ("total_contacts", models.IntegerField(default=0)),
                ("current_contact_index", models.IntegerField(default=0)),
                ("sent_messages", models.IntegerField(default=0)),
                ("failed_messages", models.IntegerField(default=0)),
                ("responded_count", models.IntegerField(default=0)),
                (
                    "next_scheduled_send",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_send_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("is_processing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("auto_pause_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="notifications.whatsappinstance",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campanha",
                "verbose_name_plural": "Campanhas",
                "db_table": "campaigns_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("is_national", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_holiday",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="CampaignMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_text", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_sent", models.IntegerField(default=0)),
                ("response_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_message",
                "ordering": ["campaign", "order"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("success", "Sucesso"),
                            ("warning", "Aviso"),
                            ("error", "Erro"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contacts.contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviada"),
                            ("delivered", "Entregue"),
                            ("read", "Lida"),
                            ("responded", "Respondeu"),
                            ("failed", "Falhou"),
                            ("skipped", "Pulado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("evolution_message_id", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_contacts",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns_participated",
                        to="contacts.contact",
                    ),
                ),
                (
                    "message_sent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaigns.campaignmessage",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_contact",
            },
        ),
        migrations.AddConstraint(
            model_name="holiday",
            constraint=models.UniqueConstraint(
                fields=("date", "tenant"), name="unique_holiday_per_date_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignmessage",
            constraint=models.UniqueConstraint(
                fields=("campaign", "order"), name="unique_message_order_per_campaign"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignlog",
            index=models.Index(
                fields=["campaign", "-created_at"],
                name="campaigns_l_campaig_419129_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigncontact",
            index=models.Index(
                fields=["campaign", "status"], name="campaigns_c_campaig_9bdcd0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigncontact",
            constraint=models.UniqueConstraint(
                fields=("campaign", "contact"), name="unique_contact_per_campaign"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant", "status", "created_at"],
                name="campaigns_c_tenant__6f1106_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["status", "is_paused", "next_scheduled_send"],
                name="campaigns_c_status_69b76b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["instance", "status"], name="campaigns_c_instanc_f580a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("instance",),
                name="unique_active_campaign_per_instance",
            ),
        ),
    ]
