# Generated by Django 4.2.25 on 2025-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="last_message_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Mensagem Enviada Em"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="next_message_scheduled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Próxima Mensagem Agendada Para"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="interval_max",
            field=models.IntegerField(
                default=50, verbose_name="Intervalo Máximo (seg)"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="interval_min",
            field=models.IntegerField(
                default=25, verbose_name="Intervalo Mínimo (seg)"
            ),
        ),
    ]
