# Generated by performance audit - 2025-10-26
# ✅ IMPROVEMENT: Add missing indexes for better query performance

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        # ✅ CRITICAL: Add indexes for Campaign model
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'status'], name='campaigns_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaigns_status_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'next_message_scheduled_at'], name='campaigns_status_next_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'created_at'], name='campaigns_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by'], name='campaigns_created_by_idx'),
        ),
        
        # ✅ CRITICAL: Add indexes for CampaignContact model
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['campaign', 'status'], name='campaign_contact_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['campaign', 'scheduled_at'], name='campaign_contact_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaign_contact_status_sched_idx'),
        ),
        
        # ✅ IMPROVEMENT: Add indexes for CampaignMessage model
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['campaign'], name='campaign_msg_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['contact'], name='campaign_msg_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['status'], name='campaign_msg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmessage',
            index=models.Index(fields=['sent_at'], name='campaign_msg_sent_idx'),
        ),
        
        # ✅ IMPROVEMENT: Add indexes for CampaignLog model
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['campaign', 'created_at'], name='campaign_log_campaign_created_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['level'], name='campaign_log_level_idx'),
        ),
    ]

