# Generated by Django 4.2.25 on 2025-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_campaign_last_message_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="pause_on_health_below",
            field=models.IntegerField(
                default=30, verbose_name="Pausar se Health Score abaixo de"
            ),
        ),
    ]
