# Generated by Django 4.2.25 on 2025-10-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_alter_campaign_pause_on_health_below"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="next_contact_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome do Próximo Contato",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="next_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Telefone do Próximo Contato",
            ),
        ),
    ]
