# Generated by Django 4.2.7 on 2025-10-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_next_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='next_instance_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Próxima Instância'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Último Contato'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Último Contato'),
        ),
    ]
