# Generated by Django 4.2.7 on 2025-10-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_create_campaign_notification'),
    ]

    operations = [
        # Índices compostos para Campaign - otimiza buscas por tenant + status
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_campaign_tenant_status 
                ON campaigns_campaign(tenant_id, status);
                
                CREATE INDEX IF NOT EXISTS idx_campaign_tenant_created 
                ON campaigns_campaign(tenant_id, created_at);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_campaign_tenant_status;
                DROP INDEX IF EXISTS idx_campaign_tenant_created;
            """
        ),
        
        # Índices compostos para CampaignContact - otimiza contadores
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_campaign_contact_campaign_status 
                ON campaigns_contact(campaign_id, status);
                
                CREATE INDEX IF NOT EXISTS idx_campaign_contact_campaign_sent 
                ON campaigns_contact(campaign_id, sent_at);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_campaign_contact_campaign_status;
                DROP INDEX IF EXISTS idx_campaign_contact_campaign_sent;
            """
        ),
    ]
