# Generated by performance audit - 2025-10-26
# ✅ IMPROVEMENT: Add missing indexes for WhatsApp instances

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # ✅ CRITICAL: Add indexes for WhatsAppInstance model using RunSQL
        migrations.RunSQL(
            sql="""
                -- WhatsAppInstance indexes (tabela: notifications_whatsapp_instance)
                CREATE INDEX IF NOT EXISTS whatsapp_tenant_default_idx 
                ON notifications_whatsapp_instance(tenant_id, is_default);
                
                CREATE INDEX IF NOT EXISTS whatsapp_tenant_state_idx 
                ON notifications_whatsapp_instance(tenant_id, connection_state);
                
                CREATE INDEX IF NOT EXISTS whatsapp_health_score_idx 
                ON notifications_whatsapp_instance(health_score);
                
                -- Remover daily_limit_reached (campo não existe no modelo)
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS whatsapp_tenant_default_idx;
                DROP INDEX IF EXISTS whatsapp_tenant_state_idx;
                DROP INDEX IF EXISTS whatsapp_health_score_idx;
                DROP INDEX IF EXISTS whatsapp_daily_limit_idx;
            """
        ),
    ]

