# Generated by performance audit - 2025-10-26
# ✅ IMPROVEMENT: Add missing indexes for WhatsApp instances

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # ✅ CRITICAL: Add indexes for WhatsAppInstance model
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['tenant', 'is_default'], name='whatsapp_tenant_default_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['tenant', 'connection_state'], name='whatsapp_tenant_state_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['health_score'], name='whatsapp_health_score_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinstance',
            index=models.Index(fields=['daily_limit_reached'], name='whatsapp_daily_limit_idx'),
        ),
    ]

