# Generated by Django 4.2.7 on 2025-10-08 23:52

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpconfig',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(help_text='Senha do email', max_length=255)),
        ),
    ]
