# Generated by Django 4.2.7 on 2025-10-08 23:53

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_smtpconfig_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(help_text='API Key da Evolution API', max_length=255)),
        ),
    ]
