# Generated by Django 4.2.7 on 2025-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_enable_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='verify_ssl',
            field=models.BooleanField(default=True, help_text='Verificar certificado SSL (desative se usar certificado auto-assinado)'),
        ),
    ]
