# Generated by Django 4.2.7 on 2025-10-09 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_smtpconfig_verify_ssl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappinstance',
            name='name',
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='connection_state',
            field=models.CharField(default='close', help_text='Estado da conexão (open, close, connecting)', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='friendly_name',
            field=models.CharField(default='Instância WhatsApp', help_text='Nome amigável para o cliente (pode repetir entre clientes)', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='qr_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='Quando o QR code expira', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='instance_name',
            field=models.CharField(help_text='Nome da instância no Evolution API (UUID interno)', max_length=100),
        ),
        migrations.CreateModel(
            name='WhatsAppConnectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Criada'), ('qr_generated', 'QR Code Gerado'), ('qr_scanned', 'QR Code Escaneado'), ('connected', 'Conectada'), ('disconnected', 'Desconectada'), ('error', 'Erro')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='notifications.whatsappinstance')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que executou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Connection Log',
                'verbose_name_plural': 'WhatsApp Connection Logs',
                'db_table': 'notifications_whatsapp_connection_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
