# Generated by Django 4.2.7 on 2025-10-09 12:31

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_whatsappinstance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='API Key da Evolution API', max_length=255)),
        ),
    ]
