# Generated by Django 4.2.7 on 2025-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_whatsappinstance_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key específica da instância', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_url',
            field=models.URLField(blank=True, help_text='URL da Evolution API (geralmente usa servidor global)', null=True),
        ),
    ]
