# Generated by Django 4.2.25 on 2025-10-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_remove_whatsapp_api_key_encryption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappinstance",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key específica da instância",
                max_length=255,
                null=True,
            ),
        ),
    ]
