# Generated by Django 4.2.25 on 2025-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="referred_by",
            field=models.CharField(
                blank=True,
                help_text="Nome de quem indicou o contato",
                max_length=200,
                null=True,
            ),
        ),
    ]
