# Generated by Django 4.2.7 on 2025-10-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_referred_by'),
    ]

    operations = [
        # Índices compostos para Contact - otimiza buscas por tenant
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_contact_tenant_phone 
                ON contacts_contact(tenant_id, phone);
                
                CREATE INDEX IF NOT EXISTS idx_contact_tenant_email 
                ON contacts_contact(tenant_id, email);
                
                CREATE INDEX IF NOT EXISTS idx_contact_tenant_active 
                ON contacts_contact(tenant_id, is_active);
                
                CREATE INDEX IF NOT EXISTS idx_contact_tenant_created 
                ON contacts_contact(tenant_id, created_at);
                
                CREATE INDEX IF NOT EXISTS idx_contact_tenant_last_purchase 
                ON contacts_contact(tenant_id, last_purchase_date);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_contact_tenant_phone;
                DROP INDEX IF EXISTS idx_contact_tenant_email;
                DROP INDEX IF EXISTS idx_contact_tenant_active;
                DROP INDEX IF EXISTS idx_contact_tenant_created;
                DROP INDEX IF EXISTS idx_contact_tenant_last_purchase;
            """
        ),
    ]
