# Generated by performance audit - 2025-10-26
# ✅ IMPROVEMENT: Add missing indexes for better query performance

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0003_add_departments'),
    ]

    operations = [
        # ✅ IMPROVEMENT: Add indexes for Department and User models using RunSQL
        migrations.RunSQL(
            sql="""
                -- Department indexes
                CREATE INDEX IF NOT EXISTS authn_dept_tenant_idx 
                ON authn_department(tenant_id);
                
                CREATE INDEX IF NOT EXISTS authn_dept_ai_enabled_idx 
                ON authn_department(ai_enabled);
                
                -- User indexes
                CREATE INDEX IF NOT EXISTS authn_user_tenant_role_idx 
                ON authn_user(tenant_id, role);
                
                CREATE INDEX IF NOT EXISTS authn_user_tenant_active_idx 
                ON authn_user(tenant_id, is_active);
                
                CREATE INDEX IF NOT EXISTS authn_user_email_idx 
                ON authn_user(email);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS authn_dept_tenant_idx;
                DROP INDEX IF EXISTS authn_dept_ai_enabled_idx;
                DROP INDEX IF EXISTS authn_user_tenant_role_idx;
                DROP INDEX IF EXISTS authn_user_tenant_active_idx;
                DROP INDEX IF EXISTS authn_user_email_idx;
            """
        ),
    ]

