# Generated by performance audit - 2025-10-26
# ✅ IMPROVEMENT: Add missing indexes for better query performance

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0003_add_departments'),
    ]

    operations = [
        # ✅ IMPROVEMENT: Add indexes for Department model
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant'], name='authn_dept_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['ai_enabled'], name='authn_dept_ai_enabled_idx'),
        ),
        
        # ✅ IMPROVEMENT: Add indexes for User model
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role'], name='authn_user_tenant_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'is_active'], name='authn_user_tenant_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authn_user_email_idx'),
        ),
    ]

