# Generated by Django 4.2.25 on 2025-10-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantproduct",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_products",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="planproduct",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_products",
                to="billing.plan",
            ),
        ),
        migrations.AddField(
            model_name="planproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_products",
                to="billing.product",
            ),
        ),
        migrations.AddField(
            model_name="billinghistory",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_history",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantproduct",
            unique_together={("tenant", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="planproduct",
            unique_together={("plan", "product")},
        ),
    ]
