# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=128)),
                ('sender', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('emotion', models.CharField(blank=True, max_length=40, null=True)),
                ('satisfaction', models.IntegerField(blank=True, null=True)),
                ('tone', models.CharField(blank=True, max_length=40, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.evolutionconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_message_embedding ON messages_message USING ivfflat (embedding vector_cosine) WITH (lists = 100);",
            reverse_sql="DROP INDEX IF EXISTS idx_message_embedding;"
        ),
    ]
