# Generated by Django 4.2.25 on 2025-10-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(db_index=True, max_length=128)),
                ("sender", models.CharField(default="unknown", max_length=64)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(db_index=True)),
                ("sentiment", models.FloatField(blank=True, null=True)),
                ("emotion", models.CharField(blank=True, max_length=40, null=True)),
                ("satisfaction", models.IntegerField(blank=True, null=True)),
                ("tone", models.CharField(blank=True, max_length=40, null=True)),
                ("summary", models.CharField(blank=True, max_length=200, null=True)),
                ("embedding", models.BinaryField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="connections.evolutionconnection",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="messages_me_created_1d508a_idx"
                    ),
                    models.Index(
                        fields=["chat_id"], name="messages_me_chat_id_702a57_idx"
                    ),
                    models.Index(fields=["text"], name="messages_me_text_d0d875_idx"),
                ],
            },
        ),
    ]
