# Generated by Django 4.2.25 on 2025-10-09 19:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="messages_me_created_1d508a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat_id"], name="messages_me_chat_id_702a57_idx"
            ),
        ),
        # migrations.AddIndex(
        #     model_name="message",
        #     index=django.contrib.postgres.indexes.GinIndex(
        #         fields=["text"], 
        #         name="messages_me_text_1bf229_gin",
        #         opclasses=["gin_trgm_ops"]
        #     ),
        # ),
    ]
