# Generated by Django 4.2.7 on 2025-10-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        # Índices compostos para Message - otimiza métricas e buscas
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS idx_message_tenant_created 
                ON chat_messages_message(tenant_id, created_at);
                
                CREATE INDEX IF NOT EXISTS idx_message_tenant_sentiment 
                ON chat_messages_message(tenant_id, sentiment);
                
                CREATE INDEX IF NOT EXISTS idx_message_tenant_satisfaction 
                ON chat_messages_message(tenant_id, satisfaction);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_message_tenant_created;
                DROP INDEX IF EXISTS idx_message_tenant_sentiment;
                DROP INDEX IF EXISTS idx_message_tenant_satisfaction;
            """
        ),
    ]
