# Generated by Django 4.2.25 on 2025-10-09 19:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_messages", "0002_message_messages_me_created_1d508a_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["text"], name="messages_me_text_1bf229_gin"
            ),
        ),
    ]
