# Generated by Django - Add metadata field to MessageAttachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_add_composite_indexes_FIXED'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='metadata',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Dados extras (processing flags, media_type, etc)',
                null=True,
                verbose_name='Metadados'
            ),
        ),
    ]

