# Generated by Django 5.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('evo_ws_url', models.URLField()),
                ('evo_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Evolution Connection',
                'verbose_name_plural': 'Evolution Connections',
                'db_table': 'connections_evolutionconnection',
            },
        ),
        migrations.AlterUniqueTogether(
            name='evolutionconnection',
            unique_together={('tenant', 'name')},
        ),
    ]
