# Generated by Django 4.2.7 on 2025-10-09 13:33

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        ('connections', '0003_add_evolution_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolutionconnection',
            options={'ordering': ['-created_at'], 'verbose_name': 'Evolution Connection', 'verbose_name_plural': 'Evolution Connections'},
        ),
        migrations.AlterUniqueTogether(
            name='evolutionconnection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evolutionconnection',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='API Key da Evolution API', max_length=255, null=True)),
        ),
        migrations.AddField(
            model_name='evolutionconnection',
            name='base_url',
            field=models.URLField(blank=True, help_text='URL base da Evolution API', null=True),
        ),
        migrations.AddField(
            model_name='evolutionconnection',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolutionconnection',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolutionconnection',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='evolutionconnection',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL do webhook para receber eventos', null=True),
        ),
        migrations.AlterField(
            model_name='evolutionconnection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evolutionconnection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evolutionconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_connections', to='tenancy.tenant'),
        ),
        migrations.RemoveField(
            model_name='evolutionconnection',
            name='evo_token',
        ),
        migrations.RemoveField(
            model_name='evolutionconnection',
            name='evo_ws_url',
        ),
    ]
