# Generated by Django 4.2.25 on 2025-10-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0001_initial"),
        ("connections", "0005_remove_api_key_encryption"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name="evolutionconnection",
        #     name="evo_token",
        # ),
        # migrations.RemoveField(
        #     model_name="evolutionconnection",
        #     name="evo_ws_url",
        # ),
        # migrations.AddField(
        #     model_name="evolutionconnection",
        #     name="api_key",
        #     field=models.CharField(
        #         blank=True,
        #         help_text="API Key da Evolution API",
        #         max_length=255,
        #         null=True,
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="evolutionconnection",
        #     name="base_url",
        #     field=models.URLField(
        #         blank=True, help_text="URL base da Evolution API", null=True
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="evolutionconnection",
        #     name="last_check",
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name="evolutionconnection",
        #     name="last_error",
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name="evolutionconnection",
        #     name="status",
        #     field=models.CharField(
        #         choices=[
        #             ("active", "Active"),
        #             ("inactive", "Inactive"),
        #             ("error", "Error"),
        #         ],
        #         default="inactive",
        #         max_length=20,
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="evolutionconnection",
        #     name="webhook_url",
        #     field=models.URLField(
        #         blank=True, help_text="URL do webhook para receber eventos", null=True
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="evolutionconnection",
        #     name="id",
        #     field=models.AutoField(primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name="evolutionconnection",
        #     name="name",
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name="evolutionconnection",
        #     name="tenant",
        #     field=models.ForeignKey(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="evolution_connections",
        #         to="tenancy.tenant",
        #     ),
        # ),
    ]
